### ISSUE TITLE
Taskbar wont move to Top.

### ISSUE THREAD

**Issue by KS-HTK** [jetspiking/Taskbar11#23] opened 2022-01-15 20:57 UTC
Pale red	Windows 11 Pro Insider Preview
Version	        Dev
Installed on	‎15/‎01/‎2022
OS build	22533.1001
Experience	Windows Feature Experience Pack 1000.22533.1001.0

I normaly use Start11 to move my taskbar to the top of the screen. After a Windows update a couple of minutes ago that feature got broken. That is why i tried this utility but it seems to suffer the same issue.
Setting the taskbar position to top and hitting save restarts explorer and the taskbar appears at the bottom.

**Comment by Setsugennoao** [comment] 2022-01-17 08:01
Up. Same problem on the same OS Build, installed on 17/01/2022.

**Comment by jetspiking** [comment] 2022-01-17 18:34
Hi there!

Thank you for reporting this issue! Could you verify whether the Windows settings menu received a new option to adjust the position to the top? I hope the functionality is not blocked just because "the taskbar isn't supposed to be used like this".

Currently I am on an older version, could you let me know when you can update to a new version and whether the issue is still present?

Thank you in advance!

**Comment by Setsugennoao** [comment] 2022-01-17 21:12
I checked in advance and no, it doesn't have any new option, unfortunately.
I really hope they didn't "fix" this permanently.
Thanks for developing this software!

**Comment by Shad8282** [comment] 2022-01-20 13:03
I have the same issue. It seems with the latest update they have fixed the way to edit the Registry to move the taskbar to top.

**Comment by SSWaltersII** [comment] 2022-01-20 22:18
Hi...
I had gotten this to work by simply changing the 03 to 01 in StuckRects3 -  several versions back on  Windows 11 Insider DEV and it persisted thru all the new builds.  Last week Acronis True Image screwed up my drive and I had to do a clean install on Win 11 Insider DEV build 22533 and now none of the "fixes" work.

**Comment by jetspiking** [comment] 2022-01-21 09:42
> Hi... I had gotten this to work by simply changing the 03 to 01 in StuckRects3 - several versions back on Windows 11 Insider DEV and it persisted thru all the new builds. Last week Acronis True Image screwed up my drive and I had to do a clean install on Win 11 Insider DEV build 22533 and now none of the "fixes" work.

Taskbar11 uses the same approach and also edits this registry key. I don't understand why Microsoft would disable this on purpose... Lets hope it is something temporary of version 22533.

**Comment by mrakobesina** [comment] 2022-01-21 12:55
same problem 
22538

**Comment by jetspiking** [comment] 2022-01-26 19:54
I also updated to version 22538 and am currently not aware of a registry solution for this issue. I will look for an alternative for a future update.

**Closed** 2022-02-14 11:56 UTC
Labels: bug

**Comment by Maaaxx1** [comment] 2022-10-16 16:28
Have the same problem with Win 11 22H2 build 22621.674 (Release)
